### ISSUE TITLE
several bug

### ISSUE THREAD

**Issue by saraiva1989** [CaiJinHao/Jh.Abp.QuickComponents#1]
A tip. Your database is open for anyone to access. This is not recommended for software development. Never place your connectstring in a public repository and if possible block access to the bank for a specific IP.
I know it's just a study screen, but you are already learning good practices.

![image](https://user-images.githubusercontent.com/40599423/105632641-02e77b80-5e33-11eb-8890-07c6792c892c.png)

**Comment by CaiJinHao** [comment]
> A tip. Your database is open for anyone to access. This is not recommended for software development. Never place your connectstring in a public repository and if possible block access to the bank for a specific IP.
> 
> I know it's just a study screen, but you are already learning good practices.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/40599423/105632641-02e77b80-5e33-11eb-8890-07c6792c892c.png)
> 
> 

Thank You
