### ISSUE TITLE
what is the benefit from this code?

### ISSUE THREAD

**Issue by mrs01dev** [CaiJinHao/Jh.Abp.QuickComponents#2]
这段代码有什么好处？
  你能提供帮助图片吗？
you have 3 modules
![image](https://user-images.githubusercontent.com/64358630/166898709-1b62bc29-b771-454a-b257-5a13aa8c0f57.png)
modules\module_extend\menu
modules\module_extend\pay
modules\module_extend\workflow

**Comment by CaiJinHao** [comment]
基于个人开发习惯而编写的基础层。这些模块的代码还没有完成。

**Comment by mrs01dev** [comment]
谢谢
